services:
  worker:
    volumes:
      - ./plugins/nomad-measurements/src/nomad_measurements:/app/plugins/nomad_measurements
      - ./plugins/nomad-measurements/src/nomad_measurements/xrd:/app/plugins/xrd
      - ./plugins/AreaA-data_modeling_and_schemas/RTG_SIMS/nomadschemartgsims:/app/plugins/nomadschemartgsims
      - ./plugins/AreaA-data_modeling_and_schemas/LayTec_EpiTT/laytec_epitt_plugin/src/laytec_epitt:/app/plugins/laytec_epitt
      - ./plugins/nomad-material-processing/src/nomad_material_processing:/app/plugins/nomad_material_processing
      - ./plugins/AreaA-data_modeling_and_schemas/PVD/PLD/jeremy_ikz/ikz_pld_plugin/src/ikz_pld:/app/plugins/ikz_pld
      - ./plugins/AreaA-data_modeling_and_schemas/hall/Lakeshore_plugin/lakeshore:/app/plugins/lakeshore     
      - ./plugins/AreaA-data_modeling_and_schemas/IKZ_plugin/src/movpe_IKZ:/app/plugins/movpe_IKZ
      - ./plugins/AreaA-data_modeling_and_schemas/IKZ_plugin/src/basesections_IKZ:/app/plugins/basesections_IKZ
      - ./plugins/AreaA-data_modeling_and_schemas/IKZ_plugin/src/movpe_substrates_IKZ:/app/plugins/movpe_substrates_IKZ
      - ./plugins/AreaA-data_modeling_and_schemas/IKZ_plugin/src/ds_IKZ:/app/plugins/ds_IKZ
      # - ./plugins/IKZ_plugin/src/cz_IKZ:/app/plugins/cz_IKZ
      
  app:
    volumes:
      - ./plugins/nomad-measurements/src/nomad_measurements:/app/plugins/nomad_measurements
      - ./plugins/nomad-measurements/src/nomad_measurements/xrd:/app/plugins/xrd
      - ./plugins/AreaA-data_modeling_and_schemas/RTG_SIMS/nomadschemartgsims:/app/plugins/nomadschemartgsims
      - ./plugins/AreaA-data_modeling_and_schemas/LayTec_EpiTT/laytec_epitt_plugin/src/laytec_epitt:/app/plugins/laytec_epitt
      - ./plugins/nomad-material-processing/src/nomad_material_processing:/app/plugins/nomad_material_processing
      - ./plugins/AreaA-data_modeling_and_schemas/PVD/PLD/jeremy_ikz/ikz_pld_plugin/src/ikz_pld:/app/plugins/ikz_pld
      - ./plugins/AreaA-data_modeling_and_schemas/hall/Lakeshore_plugin/lakeshore:/app/plugins/lakeshore
      - ./plugins/AreaA-data_modeling_and_schemas/IKZ_plugin/src/movpe_IKZ:/app/plugins/movpe_IKZ
      - ./plugins/AreaA-data_modeling_and_schemas/IKZ_plugin/src/basesections_IKZ:/app/plugins/basesections_IKZ
      - ./plugins/AreaA-data_modeling_and_schemas/IKZ_plugin/src/movpe_substrates_IKZ:/app/plugins/movpe_substrates_IKZ
      - ./plugins/AreaA-data_modeling_and_schemas/IKZ_plugin/src/ds_IKZ:/app/plugins/ds_IKZ
      # - ./plugins/IKZ_plugin/src/cz_IKZ:/app/plugins/cz_IKZ
